
listeners:
  client:
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    name: CLIENT
    sslClientAuth: "none"
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
    sslClientAuth: "none"
  interbroker:
    containerPort: 9094
    protocol: SASL_PLAINTEXT
    name: INTERNAL
    sslClientAuth: "none"
  external:
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    name: EXTERNAL
    sslClientAuth: "none"

sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN


  interbroker:
    user: inter_broker_user
    password: "Admin@Pass1"
    clientId: inter_broker_client
    clientSecret: ""

  controller:
    user: controller_user
    password: "Admin@Pass1"
    clientId: controller_broker_client
    clientSecret: ""

  client:
    users:
      - admin-user
    passwords: "Admin@Pass1"