spring:
  application:
    name: producer-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    bootstrap-servers: ${bootstrap-servers}
    properties:
      schema.registry.url: ${schema-registry-url}
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka-user} password=${kafka-password};


server:
  port: 8090


logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include:
            - ping
        readiness:
          include:
            - ping

kafka:
  bootstrapAddress: ${bootstrap-servers}