spring:
  application:
    name: demo-producer
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: kafka.default.svc.cluster.local:9092
    admin:
      fail-fast: true
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin-user" password="Admin@Pass1";


server:
  port: 8090


logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include:
            - ping
        readiness:
          include:
            - ping

kafka:
  bootstrapAddress: kafka.default.svc.cluster.local:9092