apiVersion: v1
kind: Service
metadata:
  name: schema-registry-external
  annotations:
    networking.gke.io/load-balancer-type: "External"
    cloud.google.com/load-balancer-type: "L4"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  externalTrafficPolicy: Cluster
