
auth:
  ## Parameters to configure authentication with kafka brokers
  ##
  kafka:
    saslMechanism: PLAIN

service:
  type: ClusterIP
  ports:
    http: 8081
  externalTrafficPolicy: Cluster

kafka:
  ## @param kafka.enabled Enable/disable Kafka chart installation
  ##
  enabled: false

##
## External Kafka Configuration
## All of these values are only used when kafka.enabled is set to false
##
externalKafka:
  ## @param externalKafka.brokers Array of Kafka brokers to connect to. Format: protocol://broker_hostname:port
  ##
  brokers:
    - PLAINTEXT://localhost:9092
  ## @param externalKafka.listener.protocol Kafka listener protocol. Allowed protocols: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL and SSL
  ##
  listener:
    protocol: SASL_PLAINTEXT
  sasl:
    user: "admin"
    password: "admin"
